language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
      sudo: false
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env: TOXENV=py37 NO_TESTS_OVER_WIRE=1
      sudo: true


install:
    - travis_retry pip install tox
script:
    - tox
after_success:
    - tox -e coveralls
